url: http://arsanhueza.github.io/
title: Huea
tagline: Prueba pa cachar la huea
description: "Descripcion de esta huea, cachemo que sucede"
permalink: /:title/
timezone: America/Los_Angeles

markdown: redcarpet
exclude: ["sass", "config.rb"]
